name: Android CI
on: [push, workflow_dispatch]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # خطوة هامة جداً: توليد ملف gradlew المفقود في مستودعك لتجنب الخطأ السابق
    - name: Generate missing Gradle Wrapper
      run: |
        gradle wrapper --gradle-version 8.2

    # منح صلاحية التنفيذ للملف الذي تم توليده
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # بناء التطبيق واستخراج الـ APK
    - name: Build with Gradle
      run: ./gradlew assembleDebug

    # رفع الـ APK لتبويب التحميل
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Red-hood-APK
        path: app/build/outputs/apk/debug/app-debug.apk
